# -*- coding: utf-8 -*-
"""2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16COkIeVFvPPHWIJKnHgB1oIvJ-Us4rCv
"""

# Function to determine BMI category
def determine_bmi_category(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif 18.5 <= bmi < 24.9:
        return "Normal weight"
    elif 25 <= bmi < 29.9:
        return "Overweight"
    else:
        return "Obese"

# Patient details
patient_name = "John Doe"
patient_age = 45
patient_bmi = 28.5

# Determine BMI category
bmi_category = determine_bmi_category(patient_bmi)

# Print the patient details along with BMI category
print(f"Patient Name: {patient_name}")
print(f"Patient Age: {patient_age}")
print(f"Patient BMI: {patient_bmi}")
print(f"BMI Category: {bmi_category}")