# -*- coding: utf-8 -*-
"""6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xzBHM99YBD80zZY_pi-Q5iBnCX2lhtor
"""

# Sample patient data: (Name, Weight in kg, Height in meters)
patients = [
    ("Alice", 68, 1.65),
    ("Bob", 85, 1.75),
    ("Charlie", 95, 1.80),
    ("David", 76, 1.70)
]

# Function to calculate BMI
def calculate_bmi(weight, height):
    return weight / (height ** 2)

# Add BMI to patient data
patients_with_bmi = [(name, weight, height, calculate_bmi(weight, height)) for name, weight, height in patients]

# Sort patients by BMI in descending order
sorted_patients = sorted(patients_with_bmi, key=lambda x: x[3], reverse=True)

# Print results
print("Patients sorted by BMI (highest to lowest):")
for patient in sorted_patients:
    print(f"{patient[0]} - BMI: {patient[3]:.2f}")