# -*- coding: utf-8 -*-
"""7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1blprwF6MKpgxgePR-Ecus_1DrsfJqaHX
"""

import pandas as pd

# Example DataFrame
data = {'Patient_ID': [1, 2, 3, 4, 5],
        'BMI': [22, 27, 31, 24, 29],
        'Cholesterol': [180, 220, 250, 190, 240]}

df = pd.DataFrame(data)

# Function to classify risk
def classify_risk(row):
    if row['BMI'] >= 30 or row['Cholesterol'] >= 240:
        return "High"
    elif row['BMI'] >= 25 or row['Cholesterol'] >= 200:
        return "Medium"
    else:
        return "Low"

# Apply classification
df['Risk_Level'] = df.apply(classify_risk, axis=1)

print(df)