# -*- coding: utf-8 -*-
"""Day1_Python_for_DS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10fATFq99jnHUdu5MDgv5rWRx-bNoMmCj
"""

print("Hello, Excited to start Data Science.")

customer_name = "John Doe"
customer_age = 28
customer_balance = 120.75
print("Customer:", customer_name)
print("Age:", customer_age)
print("Balance:", customer_balance)

product_price = 200
discount = product_price * 0.10
final_price = product_price - discount
product_price = 200
print("Final Price after Discount:", final_price)

import numpy as np
sales = np.array([150, 200, 250, 300, 400, 350, 500])
print("Sales Data:", sales)

print("Average Sales:", np.mean(sales))
print("Highest Sale:", np.max(sales))
print("Lowest Sale:", np.min(sales))

import pandas as pd
data = {"Customer": ["Alice", "Bob", "Charlie"],"Age": [25, 30, 35],"Amount Spent": [120, 200, 150]}
df = pd.DataFrame(data)
print(df)

from google.colab import files
import pandas as pd # Import the pandas library and assign it to the alias 'pd'
uploaded = files.upload() # Upload your CSV file
df = pd.read_csv("customers_data.csv") # Replace with your actual file name uploaded
df.head()

high_spenders = df[pd.to_numeric(df["Company"], errors='coerce') > 150]
print(high_spenders)

df_sorted = df.sort_values(by="Index", ascending=False)
print(df_sorted)

df["Loyalty Points"] = pd.to_numeric(df["Company"], errors='coerce') // 10
print(df)

df.to_csv("cleaned_customer_data.csv", index=False)
files.download("cleaned_customer_data.csv")